### ISSUE TITLE
Appliances (furnaces and campfires) not working

### ISSUE THREAD

**Issue by PrOsKiTtLeSs** [x0Z3ro0x/DKG-MC-Server#5]
Whenever you try to use a furnace or campfire, the item goes in but doesn’t cook or smelt and just stays there. But with a campfire, the food pops off automatically so it makes it so the food doesn’t ever come off without destroying the campfire

**Comment by x0Z3ro0x** [comment]
This one is truly puzzling. We have no plugins that modify the usage of furnaces or campfires. But just to make sure I removed all plugins and launched the server. The issue still continued, ruling out a plugin conflict. 

I also updated to the very latest version of spigot, the issue is still there. The reason this is puzzling is because if its not on our end, it's on spigots end, yet not one users has reported this. Which points back to our end being the cause.

To rule this out before we take this to spigot developers, I will create a fresh minecraft server and see if that too has this issue. If it does, well we know. If it doesn't well then I get to keep searching...somewhere.

**Comment by x0Z3ro0x** [comment]
Further testing only complicated the matter fml. A clean test server removed the bug, meaning the bug is on our end. However after replacing all our plugins from the current server to the test server, it still worked fine. Meaning the issue is on our end, but isn't a plugin.

This is a bug on Spigots build but is only screwing up for us. My best guess is something to do with the worlds or perhaps the cache if a Minecraft server even has one. I am going to keep attempting to solve this, and worst case, I will just replace the test server files with our files that way all our data and plugins will be saved over top a clean Spigot build. In theory this will solve the bug.

I will post again when I know more.

**Comment by x0Z3ro0x** [comment]
Alright, this is solved. After cross checking the two builds and after a crap load of eliminations, I narrowed down the only difference between the two builds which was the spigot.yml file. I do not know how or why this file caused furnaces to stop smelting, food to stop cooking, etc. None the less it's been taken care of and I bid it a good riddance.

What a weird bug to have occurred, thanks for bringing it up @PrOsKiTtLeSs
