### ISSUE TITLE
SkyBlock Arena 2

### ISSUE THREAD

**Issue by PrOsKiTtLeSs** [x0Z3ro0x/DKG-MC-Server#9]
Randomly, when fighting in arena two, it makes you leave the arena and says "Leaving so soon?" not sure if on timer, or if it is a bug

**Comment by x0Z3ro0x** [comment]
Thank you for the report! I will get on it right away.

**Comment by x0Z3ro0x** [comment]
After looking at the localization files, this is due to leaving the arena area. In Arena 2 this would be caused by parkouring to the tops of the trees, rather than staying on the arena ground. Arena 1 this is happening as a result of the arena ceiling zone being too low. If a player jumps while climbing the ramp to the fire pit, they will hit that ceiling zone and be kicked from the arena as a result. The message for such an event is "Leaving so soon?" as you described.

Arena 1 might be harder to solve than Arena 2, because literally one block higher is the spectator zones floor and glass observation deck. Off the top of my head the solution would be to just lower the physical arena floor by 1 or 2 blocks.

Arena 2 is an easier fix, but we need to make a decision. We can either expand the ceiling zone to include the tops of the trees, and spawn mobs there as well, or we need to remove access to the tree tops. Which do you feel is better for Arena 2?

I'll begin working on Arena 1 to lower the floor.

**Comment by PrOsKiTtLeSs** [comment]
I think that by removing the access to the tree tops, you're making it much harder, could we increase the height on that please

> After looking at the localization files, this is due to leaving the arena area. In Arena 2 this would be caused by parkouring to the tops of the trees, rather than staying on the arena ground. Arena 1 this is happening as a result of the arena ceiling zone being too low. If a player jumps while climbing the ramp to the fire pit, they will hit that ceiling zone and be kicked from the arena as a result. The message for such an event is "Leaving so soon?" as you described.
> 
> 
> 
> Arena 1 might be harder to solve than Arena 2, because literally one block higher is the spectator zones floor and glass observation deck. Off the top of my head the solution would be to just lower the physical arena floor by 1 or 2 blocks.
> 
> 
> 
> Arena 2 is an easier fix, but we need to make a decision. We can either expand the ceiling zone to include the tops of the trees, and spawn mobs there as well, or we need to remove access to the tree tops. Which do you feel is better for Arena 2?
> 
> 
> 
> I'll begin working on Arena 1 to lower the floor.

**Comment by x0Z3ro0x** [comment]
Alright. I will edit Arena 2 to include the tree tops.

**Comment by x0Z3ro0x** [comment]
Thanks for finding a bug and making the server better for everyone! This is fixed and tested. It works great.
